name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  HUSKY: 0 # disable Git hooks
  NODE_CURRENT_VERSION: 20
  NODE_LATEST_VERSION: 21

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_CURRENT_VERSION }}

      - name: Install dependencies
        run: npm i

      - name: Run lint
        run: npm run lint

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git diff-index --quiet HEAD || git commit -m "refactor(github-action): lint code"
          git push

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 21]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i

      - name: Run tests
        if: ${{ matrix.node-version != env.NODE_LATEST_VERSION }}
        run: npm test

      - name: Run tests coverage
        if: ${{ matrix.node-version == env.NODE_LATEST_VERSION }}
        run: npm run test:coverage

      - name: Coveralls
        if: ${{ matrix.node-version == env.NODE_LATEST_VERSION }}
        uses: coverallsapp/github-action@v2
